# Hugo Variables

# Website Info
baseURL = "https://beggarsborn.com/"
languageCode = "en-us"
title = "Lucas Weeks"
theme = "bootstrap4"
publishDir = "docs"

# optionally override the site's footer with custom copyright text
copyright = "This work is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International License](http://creativecommons.org/licenses/by-nc/4.0/)."


# Website Structure

# number of words to use for summary on home/category/tag pages
summarylength = 100

[permalinks]
  blog = "/blog/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Trinity Reformed Church"
  url = "https://trinityreformed.org"

[[menu.sidebar]]
  name = "Warhorn Media"
  url = "https://warhornmedia.com"

[[menu.navbar]]
  name = "About"
  url = "/about"
  
[[menu.navbar]]
  name = "Books"
  url = "/books"

# Theme variables
#
[params]
  # Site author
  author = "Lucas Weeks"

  # Description/subtitle for homepage (can be Markdown)
  description = "He had made many pilgrims princes, though by nature they were beggars born..."

  # Show header (default: true)
  #header_visible = true

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  sharingicons = false

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    # about = "Not sure where this will go"

    # How many posts to show on the sidebar (Default: 5)
    num_recent_posts = 5

